language: erlang
otp_release:
  - R16B
notifications:
  email: 
    - maxim@synrc.com
    - doxtop@synrc.com
  irc: "chat.freenode.net#n2o"
script: samples/mad dep com pla rel
install: "(cd samples; ./mad dep com pla)"
